name: Publish image to GHCR

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get datetime tag
        id: datetime
        run: echo "tag=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT
      
      - name: Append build timestamp to source
        run: |
          echo 'console.log("Built on: '$(date -u +%Y-%m-%dT%H:%M:%SZ)'");' >> src/index.ts

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            ghcr.io/coffee-cup/image-date-tags:latest
            ghcr.io/coffee-cup/image-date-tags:${{ steps.datetime.outputs.tag }}